### ISSUE TITLE
CLI problem

### ISSUE THREAD

**Issue by matthgyver** [AlexRudd/snapshot_grafana#1]
Hi,

I'm unable to get your project as shown on the homepage :
```
go get github.com/alexrudd/snapshot_grafana
src/github.com/alexrudd/snapshot_grafana/snapshot/snapshotClient.go:18:2: no buildable Go source files in ...
```
Could you help me please ?
Thank you

**Comment by alexrudd** [comment]
Hey,

I can't reproduce the error you're seeing when using `go get`, I did however notice of load of errors in the lib example I'd put in the README, and have corrected those.

Could you give me some more details about the problem you're having?

Thanks,
Alex

**Comment by matthgyver** [comment]
Hi,

I Discover the Go language so I just installed it from the Fedora repo (golang 1.5.4-5.fc23)
After installation, I set the env variable "GOPATH"
After that, I launch this command : 
```
go get github.com/alexrudd/snapshot_grafana
```
And I get this error : 
```
package context: unrecognized import path "context"
package github.com/prometheus/client_golang/api/prometheus: no buildable Go source files in /home/johndoe/Go/src/github.com/prometheus/client_golang/api/prometheus
```

If I raise `go get github.com/alexrudd/snapshot_grafana` I get only this error `package context: unrecognized import path "context"`
My folder contain this :
```
ls src/github.com/
alexrudd  coreos  prometheus
```

And I have not the `snapshot_grafana ` that you tell in the README.

Thank you

**Comment by alexrudd** [comment]
Okay, found a couple of problems:

One I think is with the version of Go you're using. The `context` package was only introduced in version 1.7 and you're running 1.5. Try the [official download/install page](https://golang.org/dl/).

The other problem was that I had not vendored my dependencies. I've updated the code to work with the latest Prometheus client, and used Go Dep to capture dependencies.

Hopefully should all work now!

**Comment by matthgyver** [comment]
Thank you, all it's OK now.
