### ISSUE TITLE
Failed to take snapshot: Unexpected status code: 404 Not Found

### ISSUE THREAD

**Issue by emepetres** [AlexRudd/snapshot_grafana#2]
I have the following error trying to use the CLI (tested native and docker):
```
$ ./snapshot_grafana.exe \
> -grafana_addr="http://*******:3000" \
> -grafana_api_key="***************************************************************************" \
> -dashboard_slug="mso4sc"
Failed to take snapshot: Unexpected status code: 404 Not Found
```
slug is correct, api key has admin role, using a custom installation of grafana version 4.6.0 beta3

**Comment by alexrudd** [comment]
Hey, sorry this tool is pretty old and doesn't support newer versions of Grafana. I'll mark it as achieved now
